### ISSUE TITLE
12장 cdd-블로그앱 관련 질문입니다.

### ISSUE THREAD

**Issue by readebooks** [dev-yakuza/react_with_typescript_book_examples#10]
<RegisterBlogDialog /> 유기체 컴포넌트
538 page
![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/d9358330-b557-48a6-81e5-8d7822e5988a)
있는데요.
깃허브에서 다운 받은 소스중  7버전 소스에
react_with_typescript_book_examples-main\ch12.cdd-blog\storybook-v7\src\components\organisms\RegisterBlogDialog
![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/2d1d21b9-ff2b-43d6-b165-7fa6d7373442)
적용이 되어 있지 않네요...ㅠ.ㅠ
어떻게 넣어야 되는지요?

**Comment by dev-yakuza** [comment]
@readebooks 스토리북 V7에서는 특별한 설정없이 진행이 가능하십니다.

**Comment by dev-yakuza** [comment]
@readebooks 

이전에 만들어주신 이슈에 해당 내용을 추가하였습니다.

- https://github.com/dev-yakuza/react_with_typescript_book_examples/issues/9

확인 부탁드립니다.

**Comment by dev-yakuza** [comment]
이 이슈는 [기존 이슈](https://github.com/dev-yakuza/react_with_typescript_book_examples/issues/9)에 통합되었으므로 닫도록 하겠습니다.
