### ISSUE TITLE
Lefthook 오타

### ISSUE THREAD

**Issue by readebooks** [dev-yakuza/react_with_typescript_book_examples#11]
568page
![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/df219a14-bd92-4c23-afd6-ad46e02b084d)
에서

이제 생성한 Lefthook.yml 설정을 자동으로 실행되도록 적용시켜 보자.

**Comment by dev-yakuza** [comment]
오타를 공유해주셔서 감사합니다. 부록에 관해 잘못된 부분은 다음 링크에 함께 관리하도록 하겠습니다.

- https://github.com/dev-yakuza/react_with_typescript_book_examples/issues/new
