### ISSUE TITLE
npx lefthook run pre-commit을 했는데 skip됩니다.

### ISSUE THREAD

**Issue by readebooks** [dev-yakuza/react_with_typescript_book_examples#12]
![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/a6b1e2da-aec1-4aa5-b623-c13463bfcde6)

npx lefthook run pre-commit 명령을 실행하면 대상 파일이 없다고 나옵니다. ㅠ.ㅠ
파일은 책의 내용과 동일하게 설정했습니다.

![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/357f8a61-f471-4ba1-bec6-dc6d91304295)

![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/f06af204-530d-4a06-9cf9-f1701ffa6080)

![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/bd1ba761-ab92-49aa-bf77-09ed8c918174)

**Comment by dev-yakuza** [comment]
@readebooks 혹시 `git add .`를 실행한 후, `npx lefthook run pre-commit`을 실행해보시겠어요?

**Comment by readebooks** [comment]
![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/0a589de8-96ed-41b7-af7b-1eff33b8db52)

이렇게 나옵니다.

**Comment by dev-yakuza** [comment]
지금 확인해보니, `glob`의 사양이 변경된거 같습니다.

`565` 페이지의 `lefhook.yml` 파일 내용을 다음과 같이 변경해 보시고 시도해 보시기 바랍니다.


```diff
pre-commit:
  parallel: true
  commands:
    prettier:
-     glob: './src/**'
+     root: 'src/'
      run: npm run format
    linter:
-     glob: './src/**/*.{ts,tsx}'
+     root: 'src/'
+     glob: '*.{ts,tsx}'
      run: npm run lint
```

참고한 공식 문서는 다음과 같습니다.

- https://github.com/evilmartians/lefthook/tree/master#execute-in-sub-directory

**Comment by dev-yakuza** [comment]
@readebooks 

이 이슈에서 지적해주신 내용도 다음 이슈에 작성해 두었으므로, 이 이슈는 닫도록 하겠습니다.

- https://github.com/dev-yakuza/react_with_typescript_book_examples/issues/13

혹시 문제가 계속 지속된다면 이슈를 다시 열거나 질문을 남겨주시기 바랍니다.
