### ISSUE TITLE
배포 질문요

### ISSUE THREAD

**Issue by readebooks** [dev-yakuza/react_with_typescript_book_examples#14]
cdd-blog의 경우는 
package.json 파일에
"homepage": "http://mywebsite.com/build"
추가해서 빌드하고 빌드된 파일을 서버에 업로드 한 뒤에 브라우저로 보게 되면 정상적으로 보입니다.
하지만

cdd-todo의 경우는 아래와 같이 원하는데로 표시 되지가 않습니다.
cdd-blog와 동일하게 package.json 파일에
"homepage": "http://mywebsite.com/build"
추가해서 빌드하고 빌드된 파일을 서버에 업로드 했습니다.
![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/6982eafc-4614-4b90-912e-7a36facd2e41)

아마도 cdd-blog는 single page 이고  cdd-todo는 multi page이라서 안되는거 같은데
어떻게 설정해야 되는지요?

**Comment by dev-yakuza** [comment]
@readebooks 안녕하세요.

지금까지 공부하시느라 고생하셨습니다. 🙇 

배포 내용을 보니 `/` URL이 아닌 특정 URL(`/build`)여서 문제가 되고 있는거 같습니다.

- https://stackoverflow.com/questions/49429906/how-should-i-configure-create-react-app-to-serve-app-from-subdirectory

````
<BrowserRouter basename={process.env.PUBLIC_URL} />
```

위와 같이 설정하여도 문제가 계속 발생하신다면

명령어를 사용할 때, `PUBLIC_URL`을 설정해야 할 수도 있습니다.

```
PUBLIC_URL=http://mywebsite.com/build npm run build
```

- https://bobbyhadz.com/blog/create-react-app-set-public-url


또는 `.env.production` 파일을 만들고 해당 파일에 추가해 보시기 바랍니다.

```
PUBLIC_URL=http://mywebsite.com/build
```

- https://create-react-app.dev/docs/adding-custom-environment-variables/#what-other-env-files-can-be-used

참고로 `mywebsite.com`는 예제이므로 실제 `URL`을 추가하셔야 합니다.

**Comment by readebooks** [comment]
해결했습니다. 감사합니다.

    예 http://192.168.0.8/build/ 의 경우
    (1) package.json 에 base URL 지정
      {
        ...  
        "homepage": "/build"
      }

    (2) <BrowserRouter>에 base URL 지정
      <BrowserRouter basename={process.env.PUBLIC_URL}>
      ...
      </BrowserRouter>

**Comment by dev-yakuza** [comment]
@readebooks 해결 방법을 공유해주셔서 감사합니다. 다른 분들도 참고가 되면 좋겠습니다.

문제가 해결되었으므로 이슈는 닫도록 하겠습니다.

공부하느라 고생하셨습니다.

이제 리액트를 사용하여 멋진 서비스를 개발해보시기 바랍니다. 기대하겠습니다~
