### ISSUE TITLE
ch11.cdd-todo

### ISSUE THREAD

**Issue by readebooks** [dev-yakuza/react_with_typescript_book_examples#5]
안녕하세요.. 책을 보던 중 에러가 발생하여 문의 드립니다.
 
preview.tsx 파일에
![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/e92266da-5337-43d0-8d7b-695d263048dd)

decorators를 설정하면 아래와 같은 에러가 발생합니다.
위와 같이 하면 모든 스토리에 BrowserRouter 가 적용되서 나는 에러인가 같은데 해결방법이 무엇일가요? 

![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/c56a674c-0e66-4f53-9c91-7e284b62b462)

**Comment by dev-yakuza** [comment]
@readebooks 책에 몇 페이지를 보시고 계신가요?

에러 메세지를 보면 `<Router>`안에 또 `<Rounter>`가 사용되고 있어 문제가 발생하고 있는거 같습니다.

`<BrowserRouter>`를 사용하고 있는 부분을 확인해봐야할 거 같습니다.

**Comment by readebooks** [comment]
11장 CDD - 할 일 목록 앱 407~408 페이지 입니다.
테스트 환경이 스토리북 7.4버전이라서
...
AppTitle  컴포넌트는 react-router-dom의 Link 컴포넌트를 사용하여 페이지 이동을 구현하고 있다.
따라서 이 컴포넌트를 화면에 표시하기 위해서는 react-router-dom의 BrowserRouter 컴포넌트 하위에 표시해야 한다.
AppTitle 컴포넌트를 만들 때에는 AppTitle 컴포넌트의 스토리 파일에 BrowserRouter 컴포넌트를 사용했지만,
매번 필요할 때마다 스토리 파일을 수정하는 것은 비효율적이므로 전역적으로 BrowserRouter 컴포넌트를 사용하도록 수정해 보자.
![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/2cd965a5-68ac-4e86-b8d7-fc181b6c7cae)

...
다음에 나오는 코드대로 하면 에러가 발생하여 헤매다가
gitHub에 있는 소스 다운 받아 보니 7 버전 소스가 있어서
ch11.cdd-todo\storybook-v7\.storybook\preview.tsx 파일을 적용했습니다.
하지만 위와 같은(첫 질문에 적었던) 에러가 발생합니다.

책에서는
react-router-dom이 제공하는 BrowserRouter 컴포넌트를 불러와 데코레이터 옵션에서 이를 사용하여 각각의 스토리에 적용되도록 수정했다로 마무리 하는데요...
그렇게 되면 라우터기능과 상관없는 Button, Input, Lavel 컴포넌트에도 모두 BrowserRouter 컴포넌트가 감싸게 되므로 에러가 발생하는거 아닌지요? 

저자님의 답변을 기다립니다.

**Comment by readebooks** [comment]
에러가 해결 됬습니다. 
preview.tsx에서 데코레이터로 BrowserRouter를 사용했는데...AppTitle 스토리 파일에서도 사용하고 있어서 였습니다.
제거 하니 잘 되네요...

근데 ... preview.tsx파일에 데코레이터로 BrowserRouter를 사용하게 해 놓으면 Router와 상관없는  Button, Input, Lavel 컴포넌트도 BrowserRouter로 감싸는게 아닌지요?  preview.tsx파일에 데코레이터에서  Link  컴포넌트를 사용하는 컴포넌트만 판별해서 감싸게 할 수 있는 방법은 없는 지요?

**Comment by dev-yakuza** [comment]
@readebooks 

> preview.tsx에서 데코레이터로 BrowserRouter를 사용했는데...AppTitle 스토리 파일에서도 사용하고 있어서 였습니다.
제거 하니 잘 되네요...

409 페이지의 코드가 잘못된 것을 확인했습니다.

- https://github.com/dev-yakuza/react_with_typescript_book_examples/issues/4

위의 이슈에 409 페이지 코드를 확인하시면 될거 같습니다.

> 근데 ... preview.tsx파일에 데코레이터로 BrowserRouter를 사용하게 해 놓으면 Router와 상관없는 Button, Input, Lavel 컴포넌트도 BrowserRouter로 감싸는게 아닌지요? preview.tsx파일에 데코레이터에서 Link 컴포넌트를 사용하는 컴포넌트만 판별해서 감싸게 할 수 있는 방법은 없는 지요?

`AppTitle`에서 안내한 것과 같이 각각의 스토리에 `decorator`를 적용하는 방법이 있습니다. 아래 링크는 `v7`에서 각 스토리에 따로 `decorator`를 적용하는 방법입니다. `global`에 설정하고 특정 컴포넌트에서 제거하는 방법은 없는 걸로 알고 있습니다.

- https://storybook.js.org/docs/react/writing-stories/decorators#wrap-stories-with-extra-markup

각 컴포넌트의 스토리에서 `decorator`를 설정하는 것과 `global`에 설정하고 각 컴포넌트의 스토리에서 `decrator`에 설정하지 않는 것은 개발자(또는 개발팀)의 취향에 맞게 적용하시면 될거 같습니다.


저는 스토리의 `decorator`에 대한 지식과 `Router`의 지식을 모두가 잘 알고 있다면 크게 문제가 되지 않지만 스토리북과 `Router`에 대한 이해가 부족하다면 `Router`를 사용하는 컴포넌트를 만들고 스토리에서 `decorator`를 설정하지 않아 에러가 발생하고 이를 수정하는데 시간이 많이 걸릴 수 있다고 생각하기 때문에, `global`에 설정하는 것을 선호하는 편입니다.

**Comment by dev-yakuza** [comment]
오류가 해결되셨기 때문에 이 이슈는 닫도록 하겠습니다. 또한 11장 오류 이슈에 수정 사항을 추가하였기 때문에 동일한 문제를 겪는 분들은 11장 오류 이슈를 참고해주시기 바랍니다.
