### ISSUE TITLE
419page 오류

### ISSUE THREAD

**Issue by readebooks** [dev-yakuza/react_with_typescript_book_examples#6]
![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/dc080288-5c67-4807-9a5e-15c3bff860bc)

를

![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/ae60191e-ddb3-4615-8434-f61e86993c87)
로 수정...

**Comment by dev-yakuza** [comment]
@readebooks 문제점을 공유해주셔서 감사합니다.

11장에 관련된 부분은 아래 이슈에 통합하여 관리하고 있습니다.

- https://github.com/dev-yakuza/react_with_typescript_book_examples/issues/4

지적해주신 내용도 추가하였으므로 이 이슈는 닫도록 하겠습니다.

감사합니다.
