### ISSUE TITLE
깃허브에 있는 소스에 스토리북 7버전 컨텍스트 사용하는 부분이 없습니다.ㅠ.ㅠ

### ISSUE THREAD

**Issue by readebooks** [dev-yakuza/react_with_typescript_book_examples#7]
445 page
![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/a83b5cd7-4056-4d01-a7fc-2004608df504)

를 스토리북 7버전으로 켄텍스트를 사용하게 하려고 하는데요...
깃허브 소스를 열어봤지만...

![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/f57417a8-bf15-404d-85d3-b443cf53838c)

위와 같이 켄테스트 사용하는 부분이 없네요...ㅠㅠ
어떤식으로 사용해야 되는 건지요?

**Comment by dev-yakuza** [comment]
@readebooks 

안녕하세요. 늦은 시간까지 공부하시는데, 책이 큰 도움이 되지 못하고 있는거 같아 죄송하네요. 😭 

현재 `GitHub`에 올라간 소스는 11장을 전부 진행한 상태에 코드여서 중간 부분의 결과물이 올라가 있지 않습니다. 그래서 코드를 참고하시기가 어려웠던거 같습니다.

445 페이지의 코드는 다음과 같이 수정하시면 될거 같습니다.

```tsx
import type { Meta, StoryObj } from '@storybook/react';

import { ToDoListPage } from '.';
import { ToDoListContextProvider } from 'contexts/ToDoList';

const meta = {
  title: 'Pages/ToDoListPage',
  component: ToDoListPage,
  tags: ['autodocs'],
  decorators: [
    (Story) => (
      <ToDoListContextProvider>
        <Story />
      </ToDoListContextProvider>
    ),
  ],
} satisfies Meta<typeof ToDoListPage>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
```

해당 코드는 11장 오류를 모아둔 이슈에도 작성해 두었습니다.(이 이슈는 닫도록 하겠습니다.)

- https://github.com/dev-yakuza/react_with_typescript_book_examples/issues/4

지적해주신 내용이 다른 분들께도 참고가 되었으면 좋겠습니다.

참고로 스토리북 V7의 공식 문서를 참고하시면 학습하시는데 조금 도움이 될거 같습니다.

- 공식 문서: https://storybook.js.org/docs/react/writing-stories/decorators#wrap-stories-with-extra-markup

다시 한번 불편을 드려서 죄송합니다. 🙇 

공부하시면서 또 이상한 점이 있으시면 이슈 부탁드립니다.
