### ISSUE TITLE
 ToDoList 컨텍스트 관련 질문드립니다.

### ISSUE THREAD

**Issue by readebooks** [dev-yakuza/react_with_typescript_book_examples#8]
450 page
![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/095127ae-1a26-487b-b73c-647b560208d4)

관련 질문 입니다.
InputToDo 유기체 컴포넌트의 추가 버튼 클릭시
 ToDoList 컨텍스트의 onAdd 함수가 호출될 텐데요...

할 일 추가 여부 확인 하려면 onAdd 함수 내에 콘솔 로그를 찍어야 될 거 같은데..
onAdd 함수 내에서 로그 찍게 하면 로그가 바로 입력 한 건 안 나오고 직전 항목만 나옵니다.

return 바로 위에서 로그을 찍으면 제대로 나오는데 왜 그런 건가요?
이해가 안됩니다. ㅠㅠ
ToDoList 컨텍스트의 onAdd 함수를 호출했는데 왜? ToDoListContextProvider 함수가 호출 되는 건지요?

![image](https://github.com/dev-yakuza/react_with_typescript_book_examples/assets/52492776/33bccac8-2f41-4c44-b7de-e0290a91c6bc)

**Comment by dev-yakuza** [comment]
@readebooks 보내주신 사진을 보면, `onAdd` 함수에 `console.log`는 `toDoList`를 출력하고 있습니다. 이 `toDoList`는 새로운 `toDo`가 추가되기 전, `toDoLis`이므로 입력한 건은 출력되지 않습니다. 만약 입력한 내용을 함께 출력하고 싶다면 다음과 같이 수정해야할 거 같습니다.

```tsx
const newToDoList = [...toDoList, toDo];
setToDoList(newToDoList);
console.log(newToDoList);
```

`로그가 제대로 출력된다.`의 `console.log`는 `setToDoList`를 사용하여 `State`를 업데이트하고 `re-rendering`이 발생한 후, 출력되므로 해당 `toDoList`에는 새로운 `toDo`가 포함된 내용이 됩니다.

**Comment by readebooks** [comment]
제가 모르는 부분이 많나 보네요..
1.
      const onAdd = (toDo: string) => {
          setToDoList([...toDoList, toDo]);
          console.log(toDoList); 로그가 바로 입력한건 안나오고 직전 항목만 나온다.
      };
에서 
setToDoList([...toDoList, toDo]); 가 실행되면 toDO가 바로 추가 되지 않는 건가요?
setToDoList([...toDoList, toDo]);  아래에 console.log(toDoList);  가 있으니 추가된 toDoList가 출력될 것 이라고 생각했거든요...

2. state가 수정되면 re-rendering이 발생이 발생하고 ToDoListContextProvider 함수 컴포넌트가 실행 되나 보죠?
  state에 관한 라이프사이클 관련 내용은 책에서 못 본거 같아서요...

**Comment by dev-yakuza** [comment]
@readebooks 

지금 리액트를 학습중에 계시니 모르는게 있는건 당연한거 같습니다. 그러니 너무 걱정하시 마시고 더욱 공부하시면 될거 같습니다. 💪 

1. `useState`로 만든 `setState` 함수(`setToDoList`)는 일반적인 함수와 다릅니다. 일반적인 함수(Promise 함수가 아닌 경우) 질문 주신 내용처럼, 함수에서 값이 변경되면, 그 다음 바로 변경된 값을 사용할 수 있습니다.

하지만, `setState` 함수는 일반적인 함수와 다르게 동작합니다. `setState` 함수에 값을 전달하면, `setState` 함수는 리액트에게 이 값으로 `State`를 변경하라고 알려줍니다. 그러면 리액트는 타이밍을 보고 해당 값을 변경합니다. 이렇게 값이 변경되면 해당 값을 사용하는 컴포넌트(컨텍스트)를 `re-rendering`하게 되고, 리랜더링 후 변경된 값을 사용할 수 있게 됩니다.

`setState`가 이렇게 복잡하게 동작하는 이유는 리액트가 리랜더링을 통해 컴포넌트(컨텍스트)를 다시 그리기 위해서 입니다.

따라서 `setToDoList([...toDoList, toDo]);` 시점에는 아직 `toDoList` 값이 변경된 상태가 아니므로 `console.log(toDoList);`에서는 새로운 `toDo`가 추가되지 않은 상태로 값이 출력되게 됩니다.

아래 공식 문서를 읽어보시면 이해하는데 좀 더 도움이 될거 같습니다.

- 왜 setState가 잘못된 값을 주는 걸까요?: https://ko.legacy.reactjs.org/docs/faq-state.html#why-is-setstate-giving-me-the-wrong-value

2. 컨텍스트를 설명할 때, 함수 컴포넌트와 동일하다고 설명했던거 같습니다. 그렇기 때문에 `State`를 사용하여 값을 관리한다고 설명했던거 같습니다.(책을 다시 보지 않고 답변을 달고 있기 때문에 정확하지 않습니다.)

`State`가 업데이트되면 함수 컴포넌트가 다시 실행된다고 이해해도 됩니다. 이때, 새롭게 업데이트된 `Props`나 `State`를 가지고 다시 실행됩니다.

따라서 `onAdd` 함수 밖에 있는 `console.log`는 리랜더링 후, 새로운 `State`와 함께 다시 실행되므로 새로운 `toDo`가  포함되어 출력되게 됩니다.

제 답변이 이해해 도움이 되었으면 좋겠습니다.

감사합니다.

**Comment by readebooks** [comment]
저자님!  많은 도움이 되었습니다. 감사합니다. ^^

**Comment by dev-yakuza** [comment]
@readebooks 도움이 되셨다니 다행입니다.

답변이 도움이 된거 같으니 이 이슈는 닫도록 하겠습니다.
